# Generated by Django 4.0.5 on 2025-03-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_1_alter_order_address_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='amount_method',
        ),
    ]
