# Generated by Django 4.0.5 on 2025-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_amount_paid_payment_amount_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_method',
            new_name='amount_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
